---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: "antroy/hello_who:latest"
          env:
            - name: GREETING
              value: Hey
            - name: NAME
              value: Dude
          ports:
            - containerPort: 8000
